# SPDX-FileCopyrightText: 2022-2023 Leroy Hopson <copyright@leroy.geek.nz>
# SPDX-License-Identifier: MIT
 
services:

  # Linux.
  gdtemu-linux:
    user: ${UID_GID}
    build:
      context: .
      dockerfile: linux.Dockerfile
    volumes:
      - .:/gdtemu
    working_dir: /gdtemu

  # Javascript.
  gdtemu-javascript:
    user: ${UID_GID}
    build:
      context: .
      dockerfile: javascript.Dockerfile
    volumes:
      - .:/gdtemu
    working_dir: /gdtemu

  # Windows.
  gdtemu-windows:
    user: ${UID_GID}
    build:
      context: .
      dockerfile: windows.Dockerfile
    volumes:
      - .:/gdtemu
    working_dir: /gdtemu
