name: Build TinyEMU

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libsdl2-dev
        working-directory: addons/gdtemu/native/thirdparty/TinyEMU
      - run: make
        working-directory: addons/gdtemu/native/thirdparty/TinyEMU
  build-js:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
        working-directory: addons/gdtemu/native/thirdparty/TinyEMU
      - run: docker exec emscripten make -f Makefile.js
        working-directory: addons/gdtemu/native/thirdparty/TinyEMU
  build-mac:
    runs-on: macos-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - run: brew install openssl sdl2
        working-directory: addons/gdtemu/native/thirdparty/TinyEMU
      - run: make CFLAGS=-I$(brew --prefix)/opt/openssl/include LDFLAGS=-L$(brew --prefix)/opt/openssl/lib CONFIG_MACOS=y
        working-directory: addons/gdtemu/native/thirdparty/TinyEMU
  build-ios:
    runs-on: macos-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - run: make CONFIG_IOS=y CONFIG_FS_NET= CONFIG_SDL=
        working-directory: addons/gdtemu/native/thirdparty/TinyEMU
      - run: make clean
        working-directory: addons/gdtemu/native/thirdparty/TinyEMU
      - run: make CONFIG_IOS_SIMULATOR=y CONFIG_FS_NET= CONFIG_SDL=
        working-directory: addons/gdtemu/native/thirdparty/TinyEMU
